### ISSUE TITLE
Errors running leres and/or boost on CPU

### ISSUE THREAD

**Issue by kb18951452** [thygate/stable-diffusion-webui-depthmap-script#42]
Getting this stack-trace:
```
DepthMap v0.2.7
device: cpu
Loading model weights from  ./models/leres/res101.pth
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x1D02C2AAFB0>, None, '', '', 0, 4, 384, 384, False, False, True, True, True, False, True, 1) {}
Traceback (most recent call last):
  File "C:\Users\kenne\gitrepo\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\kenne\gitrepo\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\kenne\gitrepo\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 394, in run_generate
    outputs = run_depthmap(None, outpath, imageArr, imageNameArr, compute_device, model_type, net_width, net_height, match_size, invert_depth, boost, save_depth, show_depth, show_heat, combine_output, combine_output_axis)
  File "C:\Users\kenne\gitrepo\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script\scripts\depthmap.py", line 339, in run_depthmap
    return outimages
UnboundLocalError: local variable 'outimages' referenced before assignment
```

I attempted to simply move the reference, but that we are getting the error would suggest it never had a value when running before my change, and after my change, there is no error, but also other than telling me it executed in 0.32s, nothing.

**Comment by kb18951452** [comment]
I couldn't produce any depthmaps from the prior version either, and was hoping the update would change.

**Comment by thygate** [comment]
Can you try a different model, like dpt_hybrid, and disable boost .. Does that work ?

**Comment by kb18951452** [comment]
> Can you try a different model, like dpt_hybrid, and disable boost .. Does that work ?

dpt_hybrid  and boos disabled worked.
Appreciate the quick reply. 
Thoughts on how I can turns knobs to elicit "more" depth/detail?

**Comment by thygate** [comment]
boost will give the highest detail, but try the res101 model first before enabling boost, so i can narrow down the issue ..

**Comment by kb18951452** [comment]
res101 model 
completes in < 1sec, with no results. (this is after I modified the script to avoid returning  before it was initialized.

**Comment by thygate** [comment]
Where does it fail then ? Or what changes did you make ?

**Comment by kb18951452** [comment]
I moved lines 227:
`outimages = []`
 to
 about line 130 (just made it be declared before everything. )

What works:
No boost
Using Hybrid

**Comment by kb18951452** [comment]
Turning on boost gives me no results, but it completes in < 3 seconds. 
No errors.

**Comment by thygate** [comment]
All except boost should work on CPU, I'm not sure why in your case it's not. 

What output are you getting in the console when using res101 and no boost ?

**Comment by thygate** [comment]
Could you try adding 

opt.gpu_ids[0] = -1

after line 207 reading opt = MyTestOptions().parse()

This might get boost working on cpu .. I'm not sure, please show output from console.

**Comment by thygate** [comment]
please pull the latest version, boost should now work on cpu too. Can you confirm ?

**Comment by kb18951452** [comment]
Pulled latest: 
res101 no longer produces results.
Boost does not work on any model.

**Comment by thygate** [comment]
I'm considering this issue solved, please open a new issue if problems persist.
